<?php

declare(strict_types=1);

namespace Xbot\Utils\Scheduler;

use RuntimeException;

/**
 * Scheduler for managing cron jobs
 *
 * Manages scheduled tasks, generates crontab files, and syncs with system crontab
 */
class Scheduler
{
    private string $projectRoot;
    private TaskRepository $repository;
    private string $xbotPath;
    private string $crontabFile;

    public function __construct(string $projectRoot, string $xbotPath)
    {
        $this->projectRoot = rtrim($projectRoot, '/');
        $this->repository = new TaskRepository($projectRoot);
        $this->xbotPath = $xbotPath;
        $this->crontabFile = $this->projectRoot . '/.xbot/crontab';
    }

    public function getRepository(): TaskRepository
    {
        return $this->repository;
    }

    public function addTask(Task $task): void
    {
        if ($this->repository->exists($task->getId())) {
            throw new RuntimeException(sprintf('Task already exists: %s', $task->getId()));
        }

        $this->repository->save($task);
    }

    public function updateTask(Task $task): void
    {
        if (!$this->repository->exists($task->getId())) {
            throw new RuntimeException(sprintf('Task not found: %s', $task->getId()));
        }

        $this->repository->save($task);
    }

    public function removeTask(string $taskId): void
    {
        $this->repository->delete($taskId);
    }

    public function enableTask(string $taskId): void
    {
        $task = $this->repository->find($taskId);
        if ($task === null) {
            throw new RuntimeException(sprintf('Task not found: %s', $taskId));
        }

        $task->enable();
        $this->repository->save($task);
    }

    public function disableTask(string $taskId): void
    {
        $task = $this->repository->find($taskId);
        if ($task === null) {
            throw new RuntimeException(sprintf('Task not found: %s', $taskId));
        }

        $task->disable();
        $this->repository->save($task);
    }

    public function runTask(string $taskId): int
    {
        $task = $this->repository->find($taskId);
        if ($task === null) {
            throw new RuntimeException(sprintf('Task not found: %s', $taskId));
        }

        if (!$task->isEnabled()) {
            throw new RuntimeException(sprintf('Task is disabled: %s', $taskId));
        }

        $command = $task->getCommand();
        $workingDir = $task->getWorkingDirectory() ?? $this->projectRoot;

        $descriptorspec = [
            0 => ['pipe', 'r'],
            1 => ['pipe', 'w'],
            2 => ['pipe', 'w'],
        ];

        $process = proc_open(
            $command,
            $descriptorspec,
            $pipes,
            $workingDir
        );

        if (!is_resource($process)) {
            throw new RuntimeException('Failed to execute task command');
        }

        fclose($pipes[0]);

        $stdout = stream_get_contents($pipes[1]);
        $stderr = stream_get_contents($pipes[2]);

        fclose($pipes[1]);
        fclose($pipes[2]);

        $exitCode = proc_close($process);

        if ($stdout) {
            echo $stdout;
        }

        if ($stderr) {
            fwrite(STDERR, $stderr);
        }

        return $exitCode;
    }

    public function generateCrontab(): string
    {
        $lines = [];

        $lines[] = '# XBot Scheduled Tasks';
        $lines[] = '# Generated at: ' . date('Y-m-d H:i:s');
        $lines[] = '# DO NOT EDIT THIS FILE MANUALLY';
        $lines[] = '# Use: ./bin/xbot schedule list/add/remove/enable/disable';
        $lines[] = '';

        foreach ($this->repository->getEnabledTasks() as $task) {
            $lines[] = $task->toCrontabEntry($this->xbotPath);
        }

        return implode("\n", $lines);
    }

    public function saveCrontab(): void
    {
        $crontab = $this->generateCrontab();

        $dir = dirname($this->crontabFile);
        if (!is_dir($dir)) {
            if (!mkdir($dir, 0755, true)) {
                throw new RuntimeException(sprintf('Failed to create directory: %s', $dir));
            }
        }

        $result = file_put_contents($this->crontabFile, $crontab . "\n");
        if ($result === false) {
            throw new RuntimeException(sprintf('Failed to write crontab file: %s', $this->crontabFile));
        }
    }

    public function getCrontabFile(): string
    {
        return $this->crontabFile;
    }

    public function syncToSystemCrontab(): void
    {
        $this->saveCrontab();

        $currentCrontab = $this->getSystemCrontab();

        $lines = array_filter($currentCrontab, function($line) {
            $trimmed = trim($line);
            if ($trimmed === '' || str_starts_with($trimmed, '#')) {
                return false;
            }
            return !str_contains($trimmed, 'xbot schedule run');
        });

        $newCrontab = implode("\n", $lines);
        $newCrontab .= "\n\n";
        $newCrontab .= $this->generateCrontab();

        $this->installCrontab($newCrontab);
    }

    public function removeFromSystemCrontab(): void
    {
        $currentCrontab = $this->getSystemCrontab();

        $lines = array_filter($currentCrontab, function($line) {
            $trimmed = trim($line);
            if ($trimmed === '') {
                return true;
            }
            if (str_starts_with($trimmed, '# XBot')) {
                return false;
            }
            if (str_contains($trimmed, 'xbot schedule run')) {
                return false;
            }
            return true;
        });

        $newCrontab = implode("\n", $lines);
        $this->installCrontab($newCrontab);
    }

    private function getSystemCrontab(): array
    {
        $output = [];
        $returnCode = 0;

        exec('crontab -l 2>/dev/null', $output, $returnCode);

        if ($returnCode !== 0) {
            return [];
        }

        return $output;
    }

    private function installCrontab(string $crontab): void
    {
        $tempFile = tempnam(sys_get_temp_dir(), 'crontab_');
        if ($tempFile === false) {
            throw new RuntimeException('Failed to create temporary file');
        }

        file_put_contents($tempFile, $crontab);

        $output = [];
        $returnCode = 0;
        exec(sprintf('crontab %s 2>&1', escapeshellarg($tempFile)), $output, $returnCode);

        unlink($tempFile);

        if ($returnCode !== 0) {
            throw new RuntimeException(sprintf(
                'Failed to install crontab: %s',
                implode("\n", $output)
            ));
        }
    }

    public function validateTask(Task $task): bool
    {
        try {
            if (!CronExpression::isValid($task->getCronExpression())) {
                return false;
            }

            if (empty($task->getCommand())) {
                return false;
            }

            return true;
        } catch (\Exception $e) {
            return false;
        }
    }

    public function getNextRunTime(string $taskId): ?\DateTimeImmutable
    {
        $task = $this->repository->find($taskId);
        if ($task === null) {
            return null;
        }

        $cron = new CronExpression($task->getCronExpression());
        return $cron->getNextRunDate();
    }
}
